data_program_area_name_map <-

    tibble::tribble(
        ~program_area,                             ~program_area_name,
        "HL.1",                                     "HIV/AIDS",
        "HL.2",                                           "TB",
        "HL.3",                                      "Malaria",
        "HL.4",                                          "GHS",
        "HL.5",                  "Health Systems Strenghening",
        "HL.6",                                          "MCH",
        "HL.7",                                        "FP/RH",
        "HL.8",                                         "WASH",
        "HL.9",                                    "Nutrition",
        "PO.1",                                         "PD&L",
        "DR.1",       "Conflict Mitigation and Reconciliation",
        "DR.2",                     "Democracy and Governance",
        "DR.3", "Political Competition and Consensus-Building",
        "DR.4",                                "Civil Society",
        "DR.5",                           "Peace and Security",
        "DR.6",                                 "Human Rights",
        "PO.2",                                          "A&O",
        "ES.1",                              "Basic Education",
        "EG.3",                                  "Agriculture",
        "EG.5",                  "Private Sector Productivity",
    )
usethis::use_data(data_program_area_name_map, overwrite = TRUE)

data_program_element_map <-
tibble::tribble(
    ~old_program_element, ~new_program_area,
                  "A047",            "HL.1",
                  "A048",            "HL.2",
                  "A049",            "HL.3",
                  "A050",            "HL.4",
                  "A051",            "HL.5",
                  "A052",            "HL.6",
                  "A053",            "HL.7",
                  "A054",            "HL.8",
                  "A142",            "HL.9",
                  "A141",            "PO.2",
                  "A140",            "PO.1"
    )

usethis::use_data(data_program_element_map, overwrite = TRUE)

data_program_element_name_map <-
    tibble::tribble(
    ~program_element,                                         ~program_element_name,
        "6560080.00",                                                  "6560080.00",
        "6560090.00",                                                  "6560090.00",
              "A047",                                                    "HIV/AIDS",
              "A048",                                                "Tuberculosis",
              "A049",                                                     "Malaria",
              "A051",                                 "Other Public Health Threats",
              "A052",                                   "Maternal and Child Health",
              "A053",                     "Family Planning and Reproductive Health",
              "A054",                                 "Water Supply and Sanitation",
              "A082",                     "Strengthen Microenterprise Productivity",
              "A097",                                             "Program Support",
              "A140",                                 "Program Design and Learning",
              "A141",                                "Administration and Oversight",
              "A142",                                                   "Nutrition",
            "HL.1.1",             "Preventing Mother-to-Child Transmission (PMTCT)",
           "HL.1.10",                                         "Treatment/ARV Drugs",
           "HL.1.11",                                   "Treatment/Adult Treatment",
           "HL.1.12",                                   "Laboratory Infrastructure",
           "HL.1.13",                                 "Health System Strengthening",
           "HL.1.14",                                       "Strategic Information",
           "HL.1.15",           "Biomedical Prevention - Medical Male Circumcision",
           "HL.1.16",         "Biomedical Prevention - Prevention Among Drug Users",
           "HL.1.17",                                  "Pediatric Care and Support",
           "HL.1.18",                               "Treatment/Pediatric Treatment",
           "HL.1.19",                          "Administration and Oversight (HIV)",
            "HL.1.2",                  "Sexual Prevention - Abstinence/Be Faithful",
            "HL.1.5",                 "Sexual Prevention - Other Sexual Prevention",
            "HL.1.6",                                      "Adult Care and Support",
            "HL.1.7",                                                      "TB/HIV",
            "HL.1.8",                             "Orphans and Vulnerable Children",
            "HL.1.9",                                      "Counseling and Testing",
            "HL.2.1",              "Universal Access to TB Diagnosis and Treatment",
           "HL.2.10",            "Improved Diagnosis and Treatment of Pediatric TB",
           "HL.2.11",                "Improved TB Infection Prevention and Control",
            "HL.2.2",                                 "Improved TB Drug Management",
            "HL.2.3",                  "Improved Management of TB/HIV Co-infection",
            "HL.2.4", "Programmatic Management of Multi Drug-Resistant TB (MDR-TB)",
            "HL.2.5",                              "Treatment and Support Services",
            "HL.2.7",             "Cross-cutting Health Systems Strengthening (TB)",
            "HL.2.8",                  "Host Country Strategic Information Systems",
            "HL.2.9",                                 "TB Laboratory Strengthening",
            "HL.3.1", "Diagnosis and Treatment w Artemisinin-Based Combo Therapies",
            "HL.3.2",          "Insecticide-Treated Nets (ITNs) to Prevent Malaria",
            "HL.3.3",           "Indoor Residual Spraying (IRS) to Prevent Malaria",
            "HL.3.4",         "Intermittent Preventive Treatment of Pregnant Women",
            "HL.3.6",                                            "Malaria Research",
            "HL.3.7",        "Cross-cutting Health Systems Strengthening (Malaria)",
            "HL.3.8",                         "Anti-microbial Resistance (Malaria)",
            "HL.3.9",        "Host Country Strategic Information Systems (Malaria)",
            "HL.4.1",             "Planning and Preparedness for Outbreak Response",
            "HL.4.2",                       "Animal and Human Disease Surveillance",
            "HL.4.3",                                         "Commodity Stockpile",
            "HL.4.4",                              "Behavior Change Communications",
            "HL.4.5",                                "Response to Disease Outbreak",
            "HL.4.6",          "Cross-cutting Health Systems Strengthening (PIOET)",
            "HL.4.7",          "Host Country Strategic Information Systems (PIOET)",
            "HL.6.1",                   "Birth Preparedness and Maternity Services",
           "HL.6.10",            "Host Country Strategic Information Systems (MCH)",
            "HL.6.2",       "Treatment of Obstetric Complications and Disabilities",
            "HL.6.3",                                  "Newborn Care and Treatment",
            "HL.6.4",                                                "Immunization",
            "HL.6.6",                                  "Treatment of Child Illness",
            "HL.6.8",                  "Cross-cutting Health Systems Strengthening",
            "HL.6.9",                             "Anti-microbial Resistance (MCH)",
            "HL.7.1",                                            "Service Delivery",
            "HL.7.2",              "Communication and Knowledge Management (FP/RH)",
            "HL.7.3",                       "Policy Analysis and Capacity Building",
            "HL.7.4",          "Cross-cutting Health Systems Strengthening (FP/RH)",
            "HL.7.5",          "Host Country Strategic Information Systems (FP/RH)",
            "HL.7.6",                        "Procurement and Supply Chain (FP/RH)",
            "HL.8.1",                                           "Safe Water Access",
            "HL.8.2",                                            "Basic Sanitation",
            "HL.8.3",                  "Water and Sanitation Policy and Governance",
            "HL.8.5",                                "Water Resources Productivity",
            "HL.8.8",          "Cross-cutting Health Systems Strengthening (Water)",
            "HL.9.1",                   "Promotion of Improved Nutrition Practices",
            "HL.9.2",                 "Population-based Nutrition Service Delivery",
            "HL.9.3",                 "Nutrition Enabling Environment and Capacity",
            "HL.9.4",      "Cross-cutting Health Systems Strengthening (Nutrition)",
            "HL.9.5",      "Host Country Strategic Information Systems (Nutrition)",
            "PO.1.1",                                 "Program Design and Learning",
            "PO.2.1",                                "Administration and Oversight"
    )

usethis::use_data(data_program_element_name_map, overwrite = TRUE)

