utils::globalVariables(c("sector", "award_number", "filename", "sub_sector",
                         "u_s_org_local", "period", "activity_name", "total_estimated_cost",
                         "start_date", "end_date", "aor_cor_or_activity_manager",
                         "funding_type", "pepfar_funding","obligation_type",
                         "distribution", "document_amt", "obligation_amt",
                         "subobligation_amt", "disbursement_amt", "undisbursed_amt",
                         "last_qtr_accrual_amt", "document_number", "program_area",
                         "program_element", "pipeline_amt", "bilateral_obl_number",
                         "total_disbursement_outlays", "obl_document_number",
                         "transaction_event", "transaction_amt", "transaction_event_type",
                         "active_award_number", "avg_monthly_exp_rate", "fiscal_transaction_date",
                          "active_award_number",  "document_number",
                          "transaction_disbursement", "transaction_obligation",
                         "avg_monthly_exp_rate",  "active_award_number",
                         "transaction_date", "quarter", "fiscal_year", "document_date",
                         "unliquidated_amt", "outstanding_advance_amt", "fund_status",
                         "obligation_type_filter", "distribution_filter","award_numbers",
                         "period_month", "program_area_name", "funding_office_code",
                         "fund_crcy_avail_for_subobl_amt", "fund_crcy_subcmmt_unsubobl_amt",
                         "bfy_fund", "funding_year", "actg_line", "program_sub_element",
                         "fund_fully_expired_year", "fund_cancelled_year", "fund_crcy_avail_for_subcommit_amt",
                         "implementing_mechanism", "planned_subobligations_for_the_next_months",
                         "total_obligations_this_fy", "projected_monthly_burn_rate",
                         "un_sub_obligated_funds", "planned_sub_oblig_date",
                         "approved_budget_cop_op", "unliquidated_obligations_at_the_beginning_of_the_fy",
                         "active_awards_number", "new_program_area", "commitment_type", "open_commitment_amt",
                         "bilateral_actg_line", "commitment_header_description", "commitment_source", "operating_unit",
                         "original_date", "outstanding_days_of_cmmt", "activity", "cmmt_less_than_30_days",
                         "cmmt_amt_between_31_to_90_days", "cmmt_amt_between_91_to_180_days", "cmmt_amt_above_180_days",
                         "period", "Period", "Actg Line", "Fund Fully Expired Year", "Fund Cancelled Year", "Total",
                         "Value", "program_element_name", "fund_crcy_obligation_amt", "fund_crcy_subcommitment_amt",
                         "fund_crcy_subobligation_amt", "agreement_status", "fund_crcy", "Document Number", "comments",
                         "to_be_deobligated", "status", 'Program Area', 'Program Element','Program Sub-Element',
                         "transaction_disbursement.y", "fiscal_quarter", "transaction_date_month", "transaction_date_quarter"
                         ))
